### ISSUE TITLE
For icons you can probably use Insiders debug icons

### ISSUE THREAD

**Issue by usernamehw** [Denis-net/vscode-ahk-manager#10]
https://code.visualstudio.com/insiders/

The icons will be in Stable the next release, but you can already peek them.

The play button (only without the bar before it) and square should fit the extension:

![Screenshot (39)](https://user-images.githubusercontent.com/9638156/62562427-ce23e500-b889-11e9-90ef-7838cc8c8558.png)

**Comment by usernamehw** [comment]
For `Compile` icon ... method IntelliSense icon does look a bit similar:

![Screenshot (40)](https://user-images.githubusercontent.com/9638156/62563284-5fe02200-b88b-11e9-94eb-b54db558b6f8.png)

Or Atom editor module icon:
![Screenshot (41)](https://user-images.githubusercontent.com/9638156/62563443-bbaaab00-b88b-11e9-913f-6ff709ab208e.png)

**Comment by Denis-net** [comment]
VSC has been updated !
And the icons are pretty cool !

Thank you for this suggestion, 
I'll surely improve mines with those.

The old/current were taken from the Github icons with custom colors.
Currently I'm learning Inkscape, so I'll be able to craft some SVG too.
(Unfortunately, I'm not a designer yet, I'm more a coder/fixer, but I can do it! 💪🏻)

**Comment by Denis-net** [comment]
Good evening !
Finally I have found time to update the extension !

In v 0.0.10 you can see the first icon, while in the v 0.0.11 you can see the ligthing also in the ligth theme.

What do you think about the icons ?

**Comment by usernamehw** [comment]
Much better. Thanks.
