### ISSUE TITLE
Default folder.

### ISSUE THREAD

**Issue by rediffusion** [Denis-net/vscode-ahk-manager#12]
Hello there! 😊
How can I change this path "c:\Program Files\AutoHotKey\AutoHotkey.exe"  to for example this "C:\Users\Administrator\Downloads\TEST\" ?
Regards!

**Comment by rediffusion** [comment]
Is anybody alive? Time to answer the question!

**Comment by Denis-net** [comment]
Hey @rediffusion !😊👋🏻

I stayed away from online stuffs so I didn't check Issues.
You are rigth: it's time to answer your question !

If I recall correctly you have two ways:
1) in settings `ahk.executableFullPath` for permanent change and
2) using the command `Switch Executable (Temporary)`.

Have you found a bug ?

**Comment by Denis-net** [comment]
When you specify the AutoHotkey.exe path the parent folder is used for the evaluation of the other executables (AutoHotkey.chm, WindowsSpy.ahk, etc..).
Does this answer your question ?

**Comment by rediffusion** [comment]
@Denis-net 
I have 2 versions of AutoHotkey - v2 and _H
I wonder how can I switch between 2 versions?
Now I'm doing this:
Ctrl+Shift+P > 
![image](https://user-images.githubusercontent.com/30071027/66183904-16416700-e683-11e9-9517-e6a679a133b4.png)
Thank you, the subject is closed! ✌️

**Comment by Denis-net** [comment]
What about a button that triggers a picker and allow users to switch between previously switched executables ?

The idea is:
when you switch executable it ask you "what name do you want to assign ?" and you provide  name,
a settings is composed...

A better idea has just come my mind:

What about a settings that stores :

``` JSON
{
"ahk.executableFullPaths" : [
{ "name1":"path/to/exe"},
{ "name2":"path/to/v2/exe"},
]
}
```

Then a button that triggers "AHK:Switch Executable (Temporary)", which in turn open a picker :
"name1"
"name2"
?

**Comment by rediffusion** [comment]
@Denis-net 
If you can embed this functionality, it would be great. 😊 
Do it when you have the time.  📑 ⌚

**Comment by Denis-net** [comment]
A new version is now available ! 🎉🎊

I preferred the tuples approach for performance reasons:

``` JSON
{
"ahk.executableFullPaths" : [
[ "name1", "path/to/exe"],
[ "name2", "path/to/v2/exe"],
]
}
```

But the most interesting part is : you don't have to be bothered by the JSON ! 
because you can do it interactively through the `AHK:Switch Executable (Temporary)` command. 😉

If you have further questions or any issues let me know and I'll see what I can do.

Good evening !😊👋🏻
