### ISSUE TITLE
Formatting using Tabs instead Spaces

### ISSUE THREAD

**Issue by helperman** [Denis-net/vscode-ahk-manager#13]
Could you please add an option to make indentations using Tabs, but not Spaces?
Spaces make chaos in code as well as another side effect. 
Or maybe it's just my preferable option.
I'm new to VS Code, so if you know how to make indentations by Tabs using other ways I would be grateful.

**Comment by Denis-net** [comment]
Hey @helperman 😊👋🏻

First of all: Welcome to VS Code !
(You have done a great choice)
Second, thank you for trying my extension !

My extension don't deal with syntax stuff, but I can help you:
Have you tried to click on the status bar item near the "Line Col" item ?
![immagine](https://user-images.githubusercontent.com/45769702/67151027-013e1800-f2c0-11e9-99ff-537c8854dc81.png)

I think this is what you are looking for !

**Comment by helperman** [comment]
Thanks, it helped!
