### ISSUE TITLE
Script file not found

### ISSUE THREAD

**Issue by yaronelh** [Denis-net/vscode-ahk-manager#17]
When I'm trying to stop a script, it says Script file not found, It also happens in other button
https://i.imgur.com/qL8RiZF.png

**Comment by Denis-net** [comment]
Hey @yaronelh !😊👋🏻

What version of AutoHotkey are you using ?

It seems a problem with named pipes.
The bad news is that it is the only way i can reach the AutoHotkey executable without writing into the file system.

**Comment by yaronelh** [comment]
The latest v1.1.30.01
Does it work for you?

**Comment by Denis-net** [comment]
I have just setup a VM, downloaded and installed the latest version of VSC and AHK and this is what i am seeing.

![immagine](https://user-images.githubusercontent.com/45769702/68034058-4cddc200-fcc1-11e9-9304-d82e3742aa4c.png)

What is the name of your script ?

**Comment by Denis-net** [comment]
Following this [link](https://stackoverflow.com/questions/258701/how-can-i-get-a-list-of-all-open-named-pipes-in-windows) can you list named pipes ?

Do you have the VSC's insider version ?

**Comment by yaronelh** [comment]
this is my VSC build
https://i.imgur.com/0sZtQQD.png

as for pipes searching for "\Device\NamedPipe\" yields ~450 
anything specific you're looking for?

**Comment by Denis-net** [comment]
No, nothing in particular;
The version is the same as mine.

I don't get why your extension doesn't work...
In the (Help/)DevTools you don't see anything of special ?
When you launch the run command, does it works ?
And when you open the ahk panel (Ctrl+Shift+A) do you see the error ?

You could try with a VM

**Comment by yaronelh** [comment]
1. nothing happens when I clicked Ctrl+Shift+A ,  ahk panel?

2. as for dev tools console  https://i.imgur.com/EodClFd.png

3. yes the run button does work

**Comment by Denis-net** [comment]
Yes, the ["AutoHotkey Manager"](https://raw.githubusercontent.com/Denis-net/vscode-ahk-manager/master/media/vs-ahk-manager-manager.gif) is a panel that lists all the running ahk scripts and allows you to interact with them.

If there are issues with named pipes it shouldn't work.

So the run command works, great !
In the next update i'll add a settings `ahk.useFilesInsteadOfPipes` and this will solve the problem.

Out of curiosity, 
if you try to exec the `ahk.run-buffer` command with some text selected does it work ?
Another test you could try is Sublime Text 3 + Autohotkey extension, if it allows you to run buffered(selected) text it means that VSC has issues

This is a really strange issue.
But we'll fix it 👍🏻

P.s. you could also set [keybindings](https://github.com/Denis-net/vscode-ahk-manager#known-issues)

**Comment by Denis-net** [comment]
Sorry I didn't want to close it.
I just referenced it with a commit. 😅
In a few minutes a new version will be available.
I added the `ahk.useFilesInteadOfPipes` settings, which allow you to work with this extension without named pipes.

Let me know if it works.

**Comment by yaronelh** [comment]
Just checked it out, and no it still doesn't work, It says that the file is missing.
Maybe it's something with the file path or there isn't actually file their to run?
https://i.imgur.com/4sxzqcP.png

**Comment by Denis-net** [comment]
Now it's really strange...
So you have set the `ahk.useFilesInsteadOfPipes` and VSC haven't created the script ?

When you read the error dialog you could try to check whether VSC has created the script file looking in the temp path. (Not after because after the run it deletes the file in order to free memory)

A thing that i noticed is that on your system you haven't file extensions enabled.
Please try to enable them and retry.
![immagine](https://user-images.githubusercontent.com/45769702/68301416-360fe480-00a0-11ea-8c90-23a21e7d9f69.png)
(I have an italian system, but i think you should find something similar)

Maybe is just that.

What OS do you have ?
x86 x64 ?

**Comment by yaronelh** [comment]
Once you told me that a file is being generated and deleted, I did a few tests.
for some reason if the file name has a space in it such as "aaa bbb.ahk" it fails with on error when you try to stop it or isolate it

**Comment by Denis-net** [comment]
![immagine](https://user-images.githubusercontent.com/45769702/68332101-75592800-00d6-11ea-9f36-677e07384bee.png)

Awesome: you have found it ! ✨
I never came across this issue because i was taught to never put spaces in file names;
Thank you,
Now I can fix it !

**Comment by Denis-net** [comment]
A new version is ready for you to be tested !🎊🎉

**Comment by yaronelh** [comment]
what's the version number you pushed? I don't see anything newer than the 0.0.15

**Comment by Denis-net** [comment]
0.0.16,
![immagine](https://user-images.githubusercontent.com/45769702/68392952-3628e680-016b-11ea-87f0-c3573b6c4765.png)

But:
it is marked 1 hour ago,
while i pushed and i receieved the mail yesterday:
![immagine](https://user-images.githubusercontent.com/45769702/68392991-4d67d400-016b-11ea-8cf3-df2fe78c038d.png)

I think vsc have limit regarding how often do you update an extension.

**Comment by yaronelh** [comment]
Just checked,,, the fix works at my end as well 👍👍
