### ISSUE TITLE
"Run Selected Text" DOES NOT SUPPORT Cyrillic.

### ISSUE THREAD

**Issue by rediffusion** [Denis-net/vscode-ahk-manager#21]
Don't support the Russian language!
How to fix it ?!

**Comment by Denis-net** [comment]
Hey @rediffusion 😊👋🏼
Time to answer your question ! 😜

I wasn't aware of this issue: Thanks for your feedback ! 😊

What issues are you experiencing ?
I'm not sure what i should look for, but i want to do something about it.
I have some questions that can help me to debug:

1. If you try to run "Run Selected Text" without actually select any line, does it works ?

2. Have you tried to set `ahk.useFilesInsteadOfPipes` to true and tried it again ?

3. What encoding are you using ?

4. Are there VSC extensions which i can take as an example that support Cyrillic ?

5. if i expose an encoding option, could it solve your issue ? 
    (i think the commands use the *utf-8* encoding by default)

6. Do you have a small ahk script that i can test with?
(something simple like 
```AHK 
MsgBox, "Cyrillic goes here" 
```
in a saved file if possible)

Thanks

**Comment by Denis-net** [comment]
I found some characters and what i discovered is that using "AHK Unicode" and scripts saved with "UTF-8 with BOM" it's possible to display cyrillic letters.

In version 0.0.18 I prefix all the piped commands with the UTF-8 Bom and if you switch to the Unicode AHK version this will solve the issue.
![immagine](https://user-images.githubusercontent.com/45769702/71262740-b3d23b80-2340-11ea-8ef4-ae39ec848876.png)

Let me know if it worked at your end.

**Comment by rediffusion** [comment]
1. If I don't allocate a line, the code is executed anyway. But the problem remains the same.
2. It didn't help.
3. `UTF-8 with BOM`
4. [Code Runner](https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner), but if I click `Run Script` it works fine problem is in `Run Selected Text`.
5.  On the official forum recommend for using `UTF-8 with BOM`.
6. Yes absolutely you can try a similar line:
`MsgBox, "Это текстовое сообщение..." `

Also, I've recorded the [screencast](https://www.screencast.com/t/QlYI1sze0).
 Regards! 😜

**Comment by Denis-net** [comment]
Thanks for your detailed reply ! 😄👍🏼

I guessed the right encoding:
the intresting part is that "UTF-8 with BOM" is just a regular UTF-8 prefixed by a `\ufeff`.

Here is on my side (v0.0.18 ... btw, now should be available for the download: try to restart VSC):
![CyrillicSupport](https://user-images.githubusercontent.com/45769702/71265753-2f36eb80-2347-11ea-9983-161411941c24.gif)

(I'll definely take a look at CodeRunner, maybe I'll learn something new.😉)

**Comment by rediffusion** [comment]
@Denis-net 

0Key another question...
Why I don't have this button? ʅ_(ツ)_ʃ 
I usually use ··· F1 > АHK Switch Executable (Temporary)
![image](https://user-images.githubusercontent.com/30071027/71268472-1f76d180-235e-11ea-9790-687ffd66970c.png)
This is how looks my toolbar with buttons:

![image](https://user-images.githubusercontent.com/30071027/71268536-3e756380-235e-11ea-9081-01e625ac9cd9.png)

_VSCode_ - the latest version.
_Autohotkey Manager_ - the latest version (plug-in reinstallation does not help).

**Comment by Denis-net** [comment]
Because you don't have `ahk.displaySwitchButton` set to true.😉

**Comment by Denis-net** [comment]
I'm glad it worked.
I'm closing this, feel free to reopen it if you find related bugs.
May you have a nice day !
