### ISSUE TITLE
Gif size could be reduced

### ISSUE THREAD

**Issue by usernamehw** [Denis-net/vscode-ahk-manager#9]
It's great that extension size went down from **0.06** => **0.0.9** by 10Mb, but it could be  smaller. 

I recommend using https://github.com/NickeManarin/ScreenToGif and FFmpeg encoder - should produce good quality gif with very small size.

**Comment by Denis-net** [comment]
Hey @usernamehw ! 😊👋🏻

Thanks you for the great tips:
actually, the README.md use the github's version of the gifs, while still ships with an offline copy of them.
So I can just remove them all and save more space !🎉🎊

Anyway I'll definitely give those software a try, as I need to refresh the gifs.😉👍🏻
Good evening !
